### ISSUE TITLE
Divine Visitor event crashed while attempting to duplicate a random card

### ISSUE THREAD

**Issue by andrewjsim** [erasels/SpireMapOverhaul#262]
Hi there. Having a great time with this mod but I've had a crash today. I had chosen my card to duplicate, and it appeared to crash when it was trying to choose a second, random one. I was playing Packmaster, in Act 1, on macOS 14.6.1, if any of that is relevant.

Here's the game info. Thank you for your mod and your work!

`Game crashed.
Version Info:
 - Java version (1.8.0_252)
 - Slay the Spire (12-18-2022)
 - ModTheSpire (3.30.3)
Mod list:
 - basemod (5.54.1)
 - stslib (2.11.0)
 - downfall (5.2.01)
 - coloredmap (2.4.1)
 - coloredpowertips (2.3.0)
 - mintyspire (2.5.8)
 - quickrestart (2.1.1)
 - anniv6 (1.4.6)
 - thecursed (1.1.10)
 - anniv5 (2.3.5)
 - expansionPacks (1.5.1)
 - BattleTowers (1.0.14)
 - CardAugments (1.0.5)
 - HighlightPath (0.0.3)
 - intentgraph (1.0.0)
 - rare-cards-sparkle (2.2.0)
 - RelicStats (1.2.2)
 - minigames (1.0.0)
 - wanderingMiniBosses (1.1.5)

Cause:
java.lang.IndexOutOfBoundsException: Index: 10, Size: 10
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at spireMapOverhaul.zones.divinitiesgaze.divinities.impl.Primordial.doUpdate(Primordial.java:46)
	at spireMapOverhaul.zones.divinitiesgaze.events.DivineVisitor$1.update(DivineVisitor.java:81)
	at basemod.abstracts.events.PhasedEvent.update(PhasedEvent.java:121)
	at com.megacrit.cardcrawl.rooms.EventRoom.update(EventRoom.java:30)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2532)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:876)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)`

**Comment by erasels** [comment]
Thanks for the detailed post. Will be fixed next update
